name: Node.js CI
permissions:
    contents: read

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            NODE_ENV: test

        services:
            redis:
                image: redis:latest
                ports:
                    - 6379:6379
                options: >-
                    --health-cmd "redis-cli ping || exit 1"
                    --health-interval 5s
                    --health-timeout 5s
                    --health-retries 5

        strategy:
            matrix:
                node-version: [22.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - run: npm i
            - run: npm run lint
            - name: Run Tests with Coverage
              run: npm run cover
